// ---------------------------------------------------------------------------
// Classification engine tests — exact match, contains, alias normalisation,
// auto-rule generation, personal flagging, priority ordering, pipeline stop.
// ---------------------------------------------------------------------------

import { describe, it, expect, beforeEach } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { SqliteDatabase, LedgerEngine } from "../src/index.js";
import type { Database } from "../src/index.js";

// ---------------------------------------------------------------------------
// Migration setup
// ---------------------------------------------------------------------------

const migration001 = readFileSync(
  resolve(__dirname, "../src/db/migrations/001_initial_schema.sqlite.sql"),
  "utf-8",
);
const migration004 = readFileSync(
  resolve(__dirname, "../src/db/migrations/004_bank_feeds.sqlite.sql"),
  "utf-8",
);
const migration006 = readFileSync(
  resolve(__dirname, "../src/db/migrations/006_multi_currency.sqlite.sql"),
  "utf-8",
);
const migration007 = readFileSync(
  resolve(__dirname, "../src/db/migrations/007_conversations.sqlite.sql"),
  "utf-8",
);
const migration008 = readFileSync(
  resolve(__dirname, "../src/db/migrations/008_classification.sqlite.sql"),
  "utf-8",
);

const createTestDb = async (): Promise<Database> => {
  const db = await SqliteDatabase.create();
  const schemaWithoutPragmas = migration001
    .split("\n")
    .filter((line) => !line.trim().startsWith("PRAGMA"))
    .join("\n");
  db.exec(schemaWithoutPragmas);
  db.exec(migration004);
  db.exec(migration006);
  db.exec(migration007);
  db.exec(migration008);
  return db;
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

let db: Database;
let engine: LedgerEngine;
let ledgerId: string;
let userId: string;
let expenseAccountId: string;
let saasAccountId: string;
let infraAccountId: string;

const setupLedger = async () => {
  db = await createTestDb();
  engine = new LedgerEngine(db);

  // Create user
  userId = "00000000-0000-7000-8000-000000000001";
  db.run(
    `INSERT INTO users (id, email, name, auth_provider, auth_provider_id)
     VALUES (?, ?, ?, ?, ?)`,
    [userId, "test@example.com", "Test User", "test", "test-001"],
  );

  // Create ledger
  const ledgerResult = await engine.createLedger({
    name: "Test Ledger",
    currency: "AUD",
    ownerId: userId,
  });
  ledgerId = ledgerResult.value!.id;

  // Create accounts
  const expResult = await engine.createAccount({
    ledgerId,
    name: "General Expenses",
    code: "6000",
    type: "expense",
    normalBalance: "debit",
  });
  expenseAccountId = expResult.value!.id;

  const saasResult = await engine.createAccount({
    ledgerId,
    name: "SaaS Subscriptions",
    code: "6100",
    type: "expense",
    normalBalance: "debit",
  });
  saasAccountId = saasResult.value!.id;

  const infraResult = await engine.createAccount({
    ledgerId,
    name: "Infrastructure",
    code: "6200",
    type: "expense",
    normalBalance: "debit",
  });
  infraAccountId = infraResult.value!.id;
};

describe("Classification Engine", () => {
  beforeEach(setupLedger);

  // -------------------------------------------------------------------------
  // Rule CRUD
  // -------------------------------------------------------------------------

  describe("Rule CRUD", () => {
    it("creates and retrieves a classification rule", async () => {
      const result = await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "GITHUB INC",
        targetAccountId: saasAccountId,
      });

      expect(result.ok).toBe(true);
      const rule = result.value!;
      expect(rule.ruleType).toBe("exact");
      expect(rule.field).toBe("description");
      expect(rule.pattern).toBe("GITHUB INC");
      expect(rule.targetAccountId).toBe(saasAccountId);
      expect(rule.priority).toBe(100);
      expect(rule.confidence).toBe(1.0);
      expect(rule.autoGenerated).toBe(false);
      expect(rule.hitCount).toBe(0);

      // Get by ID
      const getResult = await engine.getClassificationRule(rule.id);
      expect(getResult.ok).toBe(true);
      expect(getResult.value!.id).toBe(rule.id);
    });

    it("lists rules filtered by type", async () => {
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "GITHUB",
        targetAccountId: saasAccountId,
      });
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "contains",
        field: "description",
        pattern: "AWS",
        targetAccountId: infraAccountId,
      });

      const allResult = await engine.listClassificationRules(ledgerId);
      expect(allResult.ok).toBe(true);
      expect(allResult.value!.length).toBe(2);

      const exactOnly = await engine.listClassificationRules(ledgerId, {
        ruleType: "exact",
      });
      expect(exactOnly.value!.length).toBe(1);
      expect(exactOnly.value![0]!.ruleType).toBe("exact");
    });

    it("updates a classification rule", async () => {
      const createResult = await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "OLD PATTERN",
        targetAccountId: saasAccountId,
      });
      const ruleId = createResult.value!.id;

      const updateResult = await engine.updateClassificationRule(ruleId, {
        pattern: "NEW PATTERN",
        priority: 50,
      });
      expect(updateResult.ok).toBe(true);
      expect(updateResult.value!.pattern).toBe("NEW PATTERN");
      expect(updateResult.value!.priority).toBe(50);
    });

    it("deletes a classification rule", async () => {
      const createResult = await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "DELETE ME",
        targetAccountId: saasAccountId,
      });
      const ruleId = createResult.value!.id;

      const deleteResult = await engine.deleteClassificationRule(ruleId);
      expect(deleteResult.ok).toBe(true);

      const getResult = await engine.getClassificationRule(ruleId);
      expect(getResult.ok).toBe(false);
    });
  });

  // -------------------------------------------------------------------------
  // Classification pipeline
  // -------------------------------------------------------------------------

  describe("Classify", () => {
    it("matches an exact rule on description", async () => {
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "GITHUB INC",
        targetAccountId: saasAccountId,
      });

      const result = await engine.classifyTransaction(ledgerId, {
        description: "GITHUB INC",
      });

      expect(result.ok).toBe(true);
      expect(result.value).not.toBeNull();
      expect(result.value!.accountId).toBe(saasAccountId);
      expect(result.value!.accountCode).toBe("6100");
      expect(result.value!.layer).toBe("exact_rule");
      expect(result.value!.confidence).toBe(1.0);
    });

    it("matches case-insensitively", async () => {
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "GitHub Inc",
        targetAccountId: saasAccountId,
      });

      const result = await engine.classifyTransaction(ledgerId, {
        description: "github inc",
      });

      expect(result.ok).toBe(true);
      expect(result.value).not.toBeNull();
      expect(result.value!.accountId).toBe(saasAccountId);
    });

    it("matches a contains rule on description", async () => {
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "contains",
        field: "description",
        pattern: "AWS",
        targetAccountId: infraAccountId,
      });

      const result = await engine.classifyTransaction(ledgerId, {
        description: "AMAZON WEB SERVICES AWS 12345",
      });

      expect(result.ok).toBe(true);
      expect(result.value).not.toBeNull();
      expect(result.value!.accountId).toBe(infraAccountId);
    });

    it("matches an exact rule on category", async () => {
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "category",
        pattern: "Software",
        targetAccountId: saasAccountId,
      });

      const result = await engine.classifyTransaction(ledgerId, {
        description: "Some random desc",
        category: "Software",
      });

      expect(result.ok).toBe(true);
      expect(result.value).not.toBeNull();
      expect(result.value!.accountId).toBe(saasAccountId);
    });

    it("returns null when no rule matches", async () => {
      const result = await engine.classifyTransaction(ledgerId, {
        description: "UNKNOWN MERCHANT XYZ",
      });

      expect(result.ok).toBe(true);
      expect(result.value).toBeNull();
    });

    it("respects priority ordering (lower priority number wins)", async () => {
      // Lower priority number = higher priority
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "contains",
        field: "description",
        pattern: "AMAZON",
        targetAccountId: expenseAccountId,
        priority: 200,
      });
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "contains",
        field: "description",
        pattern: "AMAZON",
        targetAccountId: infraAccountId,
        priority: 50,
      });

      const result = await engine.classifyTransaction(ledgerId, {
        description: "AMAZON WEB SERVICES",
      });

      expect(result.ok).toBe(true);
      // Priority 50 rule should win over priority 200
      expect(result.value!.accountId).toBe(infraAccountId);
    });

    it("stops at first match (pipeline short-circuit)", async () => {
      // Exact rule should match before contains rule
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "STRIPE PAYMENTS",
        targetAccountId: saasAccountId,
      });
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "contains",
        field: "description",
        pattern: "STRIPE",
        targetAccountId: expenseAccountId,
      });

      const result = await engine.classifyTransaction(ledgerId, {
        description: "STRIPE PAYMENTS",
      });

      expect(result.ok).toBe(true);
      // Exact match should win (pipeline checks exact before contains)
      expect(result.value!.accountId).toBe(saasAccountId);
    });

    it("tracks personal flagging", async () => {
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "NETFLIX",
        targetAccountId: expenseAccountId,
        isPersonal: true,
      });

      const result = await engine.classifyTransaction(ledgerId, {
        description: "NETFLIX",
      });

      expect(result.ok).toBe(true);
      expect(result.value!.isPersonal).toBe(true);
    });

    it("increments hit count on match", async () => {
      const createResult = await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "GITHUB INC",
        targetAccountId: saasAccountId,
      });
      const ruleId = createResult.value!.id;

      // Classify twice
      await engine.classifyTransaction(ledgerId, { description: "GITHUB INC" });
      await engine.classifyTransaction(ledgerId, { description: "GITHUB INC" });

      const rule = await engine.getClassificationRule(ruleId);
      expect(rule.value!.hitCount).toBe(2);
      expect(rule.value!.lastHitAt).not.toBeNull();
    });
  });

  // -------------------------------------------------------------------------
  // Merchant alias normalisation
  // -------------------------------------------------------------------------

  describe("Merchant Aliases", () => {
    it("normalises description via alias table", async () => {
      // The migration seeds some aliases. "GITHUB.COM" should normalise to "GITHUB"
      // (seeded in the migration). Create a rule for "GITHUB".
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "GITHUB",
        targetAccountId: saasAccountId,
      });

      // "GITHUB.COM" should be normalised to "GITHUB" and match
      const result = await engine.classifyTransaction(ledgerId, {
        description: "github.com",
      });

      expect(result.ok).toBe(true);
      expect(result.value).not.toBeNull();
      expect(result.value!.accountId).toBe(saasAccountId);
    });

    it("lists and adds merchant aliases", async () => {
      const listResult = await engine.listMerchantAliases();
      expect(listResult.ok).toBe(true);
      // Should have seed data from migration
      expect(listResult.value!.length).toBeGreaterThan(0);

      // Add a new alias
      const addResult = await engine.addMerchantAlias("CUSTOM VENDOR", "CV-1234");
      expect(addResult.ok).toBe(true);
      expect(addResult.value!.canonicalName).toBe("CUSTOM VENDOR");
      expect(addResult.value!.alias).toBe("CV-1234");
    });

    it("fuzzy matches via alias variants", async () => {
      // Add a custom alias
      await engine.addMerchantAlias("MY VENDOR", "MV-PAYMENT");
      await engine.addMerchantAlias("MY VENDOR", "MV-SUBSCRIPTION");

      // Create a rule for one alias
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "MV-PAYMENT",
        targetAccountId: saasAccountId,
      });

      // The other alias should fuzzy match via the canonical name
      const result = await engine.classifyTransaction(ledgerId, {
        description: "MV-SUBSCRIPTION",
      });

      expect(result.ok).toBe(true);
      expect(result.value).not.toBeNull();
      expect(result.value!.accountId).toBe(saasAccountId);
      expect(result.value!.layer).toBe("fuzzy_match");
    });
  });

  // -------------------------------------------------------------------------
  // Auto-rule generation
  // -------------------------------------------------------------------------

  describe("Auto-rule Generation", () => {
    it("generates a rule after 2 identical classifications", async () => {
      // Create a bank connection + account for bank transactions
      const connId = "conn-001";
      const bankAcctId = "bacct-001";

      db.run(
        `INSERT INTO bank_connections (id, ledger_id, provider, provider_connection_id,
           institution_id, institution_name, status, created_at, updated_at)
         VALUES (?, ?, 'test', 'prov-conn-1', 'inst-1', 'Test Bank', 'active', datetime('now'), datetime('now'))`,
        [connId, ledgerId],
      );
      db.run(
        `INSERT INTO bank_accounts (id, connection_id, ledger_id, provider_account_id,
           name, account_number, type, currency, current_balance, created_at, updated_at)
         VALUES (?, ?, ?, 'prov-acct-1', 'Test Account', '1234', 'transaction', 'AUD', 0, datetime('now'), datetime('now'))`,
        [bankAcctId, connId, ledgerId],
      );

      // Create two bank transactions with the same description
      const btxn1 = "btxn-001";
      const btxn2 = "btxn-002";
      db.run(
        `INSERT INTO bank_transactions (id, bank_account_id, ledger_id, provider_transaction_id,
           date, amount, type, description, status, is_personal, raw_data, created_at, updated_at)
         VALUES (?, ?, ?, 'ptxn-1', '2024-01-01', 1000, 'debit', 'REPEATED VENDOR', 'pending', 0, '{}', datetime('now'), datetime('now'))`,
        [btxn1, bankAcctId, ledgerId],
      );
      db.run(
        `INSERT INTO bank_transactions (id, bank_account_id, ledger_id, provider_transaction_id,
           date, amount, type, description, status, is_personal, raw_data, created_at, updated_at)
         VALUES (?, ?, ?, 'ptxn-2', '2024-01-02', 1000, 'debit', 'REPEATED VENDOR', 'pending', 0, '{}', datetime('now'), datetime('now'))`,
        [btxn2, bankAcctId, ledgerId],
      );

      // First manual classification — should NOT create a rule (count < 2 at time of classify)
      await engine.classifyBankTransaction(btxn1, saasAccountId, false);

      let rules = await engine.listClassificationRules(ledgerId, { autoGenerated: true });
      expect(rules.value!.length).toBe(0);

      // Second manual classification — should create an auto-generated rule
      await engine.classifyBankTransaction(btxn2, saasAccountId, false);

      rules = await engine.listClassificationRules(ledgerId, { autoGenerated: true });
      expect(rules.value!.length).toBe(1);

      const autoRule = rules.value![0]!;
      expect(autoRule.ruleType).toBe("exact");
      expect(autoRule.field).toBe("description");
      expect(autoRule.pattern).toBe("REPEATED VENDOR");
      expect(autoRule.targetAccountId).toBe(saasAccountId);
      expect(autoRule.autoGenerated).toBe(true);
      expect(autoRule.confidence).toBe(0.95);
      expect(autoRule.priority).toBe(200);
    });

    it("updates auto-generated rule when classified to different account", async () => {
      // Create bank connection and transactions
      const connId = "conn-002";
      const bankAcctId = "bacct-002";

      db.run(
        `INSERT INTO bank_connections (id, ledger_id, provider, provider_connection_id,
           institution_id, institution_name, status, created_at, updated_at)
         VALUES (?, ?, 'test', 'prov-conn-2', 'inst-1', 'Test Bank', 'active', datetime('now'), datetime('now'))`,
        [connId, ledgerId],
      );
      db.run(
        `INSERT INTO bank_accounts (id, connection_id, ledger_id, provider_account_id,
           name, account_number, type, currency, current_balance, created_at, updated_at)
         VALUES (?, ?, ?, 'prov-acct-2', 'Test Account', '5678', 'transaction', 'AUD', 0, datetime('now'), datetime('now'))`,
        [bankAcctId, connId, ledgerId],
      );

      // Two transactions to trigger auto-rule for saasAccountId
      for (let i = 0; i < 2; i++) {
        const id = `btxn-upd-${i}`;
        db.run(
          `INSERT INTO bank_transactions (id, bank_account_id, ledger_id, provider_transaction_id,
             date, amount, type, description, status, is_personal, raw_data, created_at, updated_at)
           VALUES (?, ?, ?, ?, '2024-01-0${i + 1}', 2000, 'debit', 'SWITCH VENDOR', 'pending', 0, '{}', datetime('now'), datetime('now'))`,
          [id, bankAcctId, ledgerId, `ptxn-upd-${i}`],
        );
        await engine.classifyBankTransaction(id, saasAccountId, false);
      }

      let rules = await engine.listClassificationRules(ledgerId, { autoGenerated: true });
      expect(rules.value!.length).toBe(1);
      expect(rules.value![0]!.targetAccountId).toBe(saasAccountId);

      // Now classify one to a different account — should update the rule
      const btxn3 = "btxn-upd-3";
      db.run(
        `INSERT INTO bank_transactions (id, bank_account_id, ledger_id, provider_transaction_id,
           date, amount, type, description, status, is_personal, raw_data, created_at, updated_at)
         VALUES (?, ?, ?, 'ptxn-upd-3', '2024-01-03', 2000, 'debit', 'SWITCH VENDOR', 'pending', 0, '{}', datetime('now'), datetime('now'))`,
        [btxn3, bankAcctId, ledgerId],
      );
      await engine.classifyBankTransaction(btxn3, infraAccountId, false);

      rules = await engine.listClassificationRules(ledgerId, { autoGenerated: true });
      expect(rules.value!.length).toBe(1);
      expect(rules.value![0]!.targetAccountId).toBe(infraAccountId);
    });
  });

  // -------------------------------------------------------------------------
  // Batch classification of pending bank transactions
  // -------------------------------------------------------------------------

  describe("Batch Classification", () => {
    it("classifies pending bank transactions", async () => {
      // Setup bank connection and account
      const connId = "conn-batch";
      const bankAcctId = "bacct-batch";

      db.run(
        `INSERT INTO bank_connections (id, ledger_id, provider, provider_connection_id,
           institution_id, institution_name, status, created_at, updated_at)
         VALUES (?, ?, 'test', 'prov-conn-b', 'inst-1', 'Test Bank', 'active', datetime('now'), datetime('now'))`,
        [connId, ledgerId],
      );
      db.run(
        `INSERT INTO bank_accounts (id, connection_id, ledger_id, provider_account_id,
           name, account_number, type, currency, current_balance, created_at, updated_at)
         VALUES (?, ?, ?, 'prov-acct-b', 'Test Account', '9999', 'transaction', 'AUD', 0, datetime('now'), datetime('now'))`,
        [bankAcctId, connId, ledgerId],
      );

      // Create rules
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "exact",
        field: "description",
        pattern: "GITHUB INC",
        targetAccountId: saasAccountId,
        confidence: 1.0,
      });
      await engine.createClassificationRule({
        ledgerId,
        ruleType: "contains",
        field: "description",
        pattern: "MAYBE MATCH",
        targetAccountId: expenseAccountId,
        confidence: 0.75,
      });

      // Create pending bank transactions
      db.run(
        `INSERT INTO bank_transactions (id, bank_account_id, ledger_id, provider_transaction_id,
           date, amount, type, description, status, is_personal, raw_data, created_at, updated_at)
         VALUES ('bt-batch-1', ?, ?, 'pt-b-1', '2024-01-01', 1000, 'debit', 'GITHUB INC', 'pending', 0, '{}', datetime('now'), datetime('now'))`,
        [bankAcctId, ledgerId],
      );
      db.run(
        `INSERT INTO bank_transactions (id, bank_account_id, ledger_id, provider_transaction_id,
           date, amount, type, description, status, is_personal, raw_data, created_at, updated_at)
         VALUES ('bt-batch-2', ?, ?, 'pt-b-2', '2024-01-02', 2000, 'debit', 'MAYBE MATCH SOMETHING', 'pending', 0, '{}', datetime('now'), datetime('now'))`,
        [bankAcctId, ledgerId],
      );
      db.run(
        `INSERT INTO bank_transactions (id, bank_account_id, ledger_id, provider_transaction_id,
           date, amount, type, description, status, is_personal, raw_data, created_at, updated_at)
         VALUES ('bt-batch-3', ?, ?, 'pt-b-3', '2024-01-03', 3000, 'debit', 'UNKNOWN MERCHANT', 'pending', 0, '{}', datetime('now'), datetime('now'))`,
        [bankAcctId, ledgerId],
      );

      const result = await engine.classifyPendingBankTransactions(ledgerId);
      expect(result.ok).toBe(true);
      expect(result.value!.classified).toBe(1); // GITHUB INC (conf 1.0 >= 0.95)
      expect(result.value!.suggested).toBe(1); // MAYBE MATCH (conf 0.75 >= 0.60)
      expect(result.value!.unclassified).toBe(1); // UNKNOWN MERCHANT

      // Verify the classified transaction is now matched
      const bt1 = await db.get<{ status: string; suggested_account_id: string }>(
        "SELECT status, suggested_account_id FROM bank_transactions WHERE id = 'bt-batch-1'",
      );
      expect(bt1!.status).toBe("matched");
      expect(bt1!.suggested_account_id).toBe(saasAccountId);

      // Suggested transaction stays pending but has suggestion
      const bt2 = await db.get<{ status: string; suggested_account_id: string }>(
        "SELECT status, suggested_account_id FROM bank_transactions WHERE id = 'bt-batch-2'",
      );
      expect(bt2!.status).toBe("pending");
      expect(bt2!.suggested_account_id).toBe(expenseAccountId);

      // Unclassified stays pending with no suggestion
      const bt3 = await db.get<{ status: string; suggested_account_id: string | null }>(
        "SELECT status, suggested_account_id FROM bank_transactions WHERE id = 'bt-batch-3'",
      );
      expect(bt3!.status).toBe("pending");
      expect(bt3!.suggested_account_id).toBeNull();
    });
  });
});
