// ---------------------------------------------------------------------------
// Classification rules CRUD — create, list, update, delete, auto-generate.
// ---------------------------------------------------------------------------

import type { Database } from "../db/database.js";
import type { Result } from "../types/index.js";
import type {
  ClassificationRule,
  ClassificationRuleRow,
  CreateClassificationRuleInput,
  UpdateClassificationRuleInput,
  ListClassificationRulesOptions,
} from "./types.js";
import { toClassificationRule } from "./types.js";
import { generateId, nowUtc } from "../engine/id.js";
import { ok, err, createError, ErrorCode } from "../errors/index.js";

export interface RulesService {
  createRule(input: CreateClassificationRuleInput): Promise<Result<ClassificationRule>>;
  listRules(ledgerId: string, opts?: ListClassificationRulesOptions): Promise<Result<readonly ClassificationRule[]>>;
  getRule(ruleId: string): Promise<Result<ClassificationRule>>;
  updateRule(ruleId: string, input: UpdateClassificationRuleInput): Promise<Result<ClassificationRule>>;
  deleteRule(ruleId: string): Promise<Result<void>>;
  autoGenerateRule(
    ledgerId: string,
    description: string,
    accountId: string,
    isPersonal: boolean,
  ): Promise<Result<ClassificationRule | null>>;
}

export const classificationRuleNotFoundError = (id: string) =>
  createError(ErrorCode.INTERNAL_ERROR, `Classification rule not found: ${id}`, [
    {
      field: "ruleId",
      actual: id,
      suggestion: "Verify the classification rule ID is correct. Use GET /v1/classification/rules to list rules.",
    },
  ]);

export function createRulesService(db: Database): RulesService {
  return {
    async createRule(input: CreateClassificationRuleInput): Promise<Result<ClassificationRule>> {
      const id = generateId();
      const ts = nowUtc();

      await db.run(
        `INSERT INTO classification_rules
           (id, ledger_id, priority, rule_type, field, pattern, target_account_id,
            is_personal, confidence, auto_generated, hit_count, created_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?)`,
        [
          id,
          input.ledgerId,
          input.priority ?? 100,
          input.ruleType,
          input.field,
          input.pattern,
          input.targetAccountId,
          input.isPersonal ? 1 : 0,
          input.confidence ?? 1.0,
          0, // manual creation = not auto-generated
          ts,
        ],
      );

      const row = await db.get<ClassificationRuleRow>(
        "SELECT * FROM classification_rules WHERE id = ?",
        [id],
      );
      return ok(toClassificationRule(row!));
    },

    async listRules(
      ledgerId: string,
      opts: ListClassificationRulesOptions = {},
    ): Promise<Result<readonly ClassificationRule[]>> {
      const conditions: string[] = ["ledger_id = ?"];
      const params: unknown[] = [ledgerId];

      if (opts.ruleType) {
        conditions.push("rule_type = ?");
        params.push(opts.ruleType);
      }
      if (opts.field) {
        conditions.push("field = ?");
        params.push(opts.field);
      }
      if (opts.autoGenerated !== undefined) {
        conditions.push("auto_generated = ?");
        params.push(opts.autoGenerated ? 1 : 0);
      }

      const limit = opts.limit ?? 200;
      const offset = opts.offset ?? 0;
      params.push(limit, offset);

      const rows = await db.all<ClassificationRuleRow>(
        `SELECT * FROM classification_rules
         WHERE ${conditions.join(" AND ")}
         ORDER BY priority ASC, created_at ASC
         LIMIT ? OFFSET ?`,
        params,
      );

      return ok(rows.map(toClassificationRule));
    },

    async getRule(ruleId: string): Promise<Result<ClassificationRule>> {
      const row = await db.get<ClassificationRuleRow>(
        "SELECT * FROM classification_rules WHERE id = ?",
        [ruleId],
      );
      if (!row) return err(classificationRuleNotFoundError(ruleId));
      return ok(toClassificationRule(row));
    },

    async updateRule(
      ruleId: string,
      input: UpdateClassificationRuleInput,
    ): Promise<Result<ClassificationRule>> {
      const existing = await db.get<ClassificationRuleRow>(
        "SELECT * FROM classification_rules WHERE id = ?",
        [ruleId],
      );
      if (!existing) return err(classificationRuleNotFoundError(ruleId));

      const sets: string[] = [];
      const params: unknown[] = [];

      if (input.priority !== undefined) {
        sets.push("priority = ?");
        params.push(input.priority);
      }
      if (input.pattern !== undefined) {
        sets.push("pattern = ?");
        params.push(input.pattern);
      }
      if (input.targetAccountId !== undefined) {
        sets.push("target_account_id = ?");
        params.push(input.targetAccountId);
      }
      if (input.isPersonal !== undefined) {
        sets.push("is_personal = ?");
        params.push(input.isPersonal ? 1 : 0);
      }
      if (input.confidence !== undefined) {
        sets.push("confidence = ?");
        params.push(input.confidence);
      }

      if (sets.length > 0) {
        params.push(ruleId);
        await db.run(
          `UPDATE classification_rules SET ${sets.join(", ")} WHERE id = ?`,
          params,
        );
      }

      const row = await db.get<ClassificationRuleRow>(
        "SELECT * FROM classification_rules WHERE id = ?",
        [ruleId],
      );
      return ok(toClassificationRule(row!));
    },

    async deleteRule(ruleId: string): Promise<Result<void>> {
      const existing = await db.get<ClassificationRuleRow>(
        "SELECT * FROM classification_rules WHERE id = ?",
        [ruleId],
      );
      if (!existing) return err(classificationRuleNotFoundError(ruleId));

      await db.run("DELETE FROM classification_rules WHERE id = ?", [ruleId]);
      return ok(undefined);
    },

    /**
     * Auto-generate rule after repeated identical classifications.
     *
     * Called when a user manually classifies a bank transaction. Tracks how
     * many times the same normalised description has been classified to the
     * same account. On the 2nd identical classification, create an exact-match
     * rule with auto_generated = true.
     *
     * Returns the created rule, or null if not yet at the threshold.
     */
    async autoGenerateRule(
      ledgerId: string,
      description: string,
      accountId: string,
      isPersonal: boolean,
    ): Promise<Result<ClassificationRule | null>> {
      const normalisedPattern = description.trim().toUpperCase();

      // Check if an auto-generated rule already exists for this exact pattern + account
      const existing = await db.get<ClassificationRuleRow>(
        `SELECT * FROM classification_rules
         WHERE ledger_id = ? AND auto_generated = 1 AND rule_type = 'exact'
           AND field = 'description' AND UPPER(pattern) = ?`,
        [ledgerId, normalisedPattern],
      );

      if (existing) {
        // Rule already exists — if targeting same account, nothing to do
        if (existing.target_account_id === accountId) {
          return ok(toClassificationRule(existing));
        }
        // If targeting a different account, update the existing auto-generated rule
        await db.run(
          `UPDATE classification_rules
           SET target_account_id = ?, is_personal = ?
           WHERE id = ?`,
          [accountId, isPersonal ? 1 : 0, existing.id],
        );
        const updated = await db.get<ClassificationRuleRow>(
          "SELECT * FROM classification_rules WHERE id = ?",
          [existing.id],
        );
        return ok(toClassificationRule(updated!));
      }

      // Count how many bank transactions with this description have been
      // classified to this same account
      const countRow = await db.get<{ cnt: number }>(
        `SELECT COUNT(*) as cnt FROM bank_transactions
         WHERE ledger_id = ? AND UPPER(description) = ?
           AND suggested_account_id = ? AND status IN ('matched', 'posted')`,
        [ledgerId, normalisedPattern, accountId],
      );

      const count = countRow?.cnt ?? 0;

      // Need at least 2 identical classifications to auto-generate
      if (count < 2) {
        return ok(null);
      }

      // Create auto-generated exact-match rule
      const id = generateId();
      const ts = nowUtc();

      await db.run(
        `INSERT INTO classification_rules
           (id, ledger_id, priority, rule_type, field, pattern, target_account_id,
            is_personal, confidence, auto_generated, hit_count, created_at)
         VALUES (?, ?, ?, 'exact', 'description', ?, ?, ?, 0.95, 1, 0, ?)`,
        [id, ledgerId, 200, normalisedPattern, accountId, isPersonal ? 1 : 0, ts],
      );

      const row = await db.get<ClassificationRuleRow>(
        "SELECT * FROM classification_rules WHERE id = ?",
        [id],
      );
      return ok(toClassificationRule(row!));
    },
  };
}
