// ---------------------------------------------------------------------------
// Classification types — rules engine for auto-categorising bank transactions.
// ---------------------------------------------------------------------------

export type RuleType = "exact" | "contains" | "regex" | "amount_range";
export type RuleField = "description" | "merchant_name" | "category";
export type ClassificationLayer = "exact_rule" | "fuzzy_match" | "ai_suggestion";

export interface ClassificationRule {
  readonly id: string;
  readonly ledgerId: string;
  readonly priority: number;
  readonly ruleType: RuleType;
  readonly field: RuleField;
  readonly pattern: string;
  readonly targetAccountId: string;
  readonly isPersonal: boolean;
  readonly confidence: number;
  readonly autoGenerated: boolean;
  readonly hitCount: number;
  readonly lastHitAt: string | null;
  readonly createdAt: string;
}

export interface MerchantAlias {
  readonly id: string;
  readonly canonicalName: string;
  readonly alias: string;
  readonly createdAt: string;
}

export interface ClassificationResult {
  readonly accountId: string;
  readonly accountCode: string;
  readonly accountName: string;
  readonly isPersonal: boolean;
  readonly confidence: number;
  readonly ruleId: string | null;
  readonly layer: ClassificationLayer;
}

// ---------------------------------------------------------------------------
// DB row types (snake_case)
// ---------------------------------------------------------------------------

export interface ClassificationRuleRow {
  id: string;
  ledger_id: string;
  priority: number;
  rule_type: string;
  field: string;
  pattern: string;
  target_account_id: string;
  is_personal: number | boolean;
  confidence: number;
  auto_generated: number | boolean;
  hit_count: number;
  last_hit_at: string | null;
  created_at: string;
}

export interface MerchantAliasRow {
  id: string;
  canonical_name: string;
  alias: string;
  created_at: string;
}

// ---------------------------------------------------------------------------
// Input types
// ---------------------------------------------------------------------------

export interface CreateClassificationRuleInput {
  readonly ledgerId: string;
  readonly priority?: number;
  readonly ruleType: RuleType;
  readonly field: RuleField;
  readonly pattern: string;
  readonly targetAccountId: string;
  readonly isPersonal?: boolean;
  readonly confidence?: number;
}

export interface UpdateClassificationRuleInput {
  readonly priority?: number;
  readonly pattern?: string;
  readonly targetAccountId?: string;
  readonly isPersonal?: boolean;
  readonly confidence?: number;
}

export interface ListClassificationRulesOptions {
  readonly ruleType?: RuleType;
  readonly field?: RuleField;
  readonly autoGenerated?: boolean;
  readonly limit?: number;
  readonly offset?: number;
}

// ---------------------------------------------------------------------------
// Row converters
// ---------------------------------------------------------------------------

export const toClassificationRule = (row: ClassificationRuleRow): ClassificationRule => ({
  id: row.id,
  ledgerId: row.ledger_id,
  priority: row.priority,
  ruleType: row.rule_type as RuleType,
  field: row.field as RuleField,
  pattern: row.pattern,
  targetAccountId: row.target_account_id,
  isPersonal: row.is_personal === 1 || row.is_personal === true,
  confidence: row.confidence,
  autoGenerated: row.auto_generated === 1 || row.auto_generated === true,
  hitCount: row.hit_count,
  lastHitAt: row.last_hit_at,
  createdAt: row.created_at,
});

export const toMerchantAlias = (row: MerchantAliasRow): MerchantAlias => ({
  id: row.id,
  canonicalName: row.canonical_name,
  alias: row.alias,
  createdAt: row.created_at,
});
