// ---------------------------------------------------------------------------
// Classification routes — /v1/ledgers/:ledgerId/classification
//
// CRUD for classification rules, classify preview, manual bank transaction
// classification.
// ---------------------------------------------------------------------------

import { Hono } from "hono";
import type { Env } from "../lib/context.js";
import { apiKeyAuth } from "../middleware/auth.js";
import { errorResponse, created, success } from "../lib/responses.js";
import { createError, ErrorCode } from "@ledge/core";
import type { RuleType, RuleField } from "@ledge/core";

export const classificationRoutes = new Hono<Env>();

classificationRoutes.use("/*", apiKeyAuth);

// ---------------------------------------------------------------------------
// Rules CRUD
// ---------------------------------------------------------------------------

/** GET /v1/ledgers/:ledgerId/classification/rules — List classification rules */
classificationRoutes.get("/rules", async (c) => {
  const engine = c.get("engine");
  const ledgerId = c.req.param("ledgerId")!;

  const ruleType = c.req.query("ruleType") as RuleType | undefined;
  const field = c.req.query("field") as RuleField | undefined;
  const autoGeneratedStr = c.req.query("autoGenerated");
  const autoGenerated = autoGeneratedStr !== undefined
    ? autoGeneratedStr === "true"
    : undefined;
  const limitStr = c.req.query("limit");
  const limit = limitStr ? parseInt(limitStr, 10) : undefined;
  const offsetStr = c.req.query("offset");
  const offset = offsetStr ? parseInt(offsetStr, 10) : undefined;

  const result = await engine.listClassificationRules(ledgerId, {
    ruleType,
    field,
    autoGenerated,
    limit,
    offset,
  });
  if (!result.ok) return errorResponse(c, result.error);

  return success(c, result.value);
});

/** POST /v1/ledgers/:ledgerId/classification/rules — Create classification rule */
classificationRoutes.post("/rules", async (c) => {
  const engine = c.get("engine");
  const ledgerId = c.req.param("ledgerId")!;
  const body = await c.req.json();

  if (!body.ruleType || !body.field || !body.pattern || !body.targetAccountId) {
    return errorResponse(
      c,
      createError(ErrorCode.VALIDATION_ERROR, "Missing required fields", [
        {
          field: "ruleType, field, pattern, targetAccountId",
          suggestion:
            "Provide ruleType (exact|contains|regex|amount_range), field (description|merchant_name|category), pattern, and targetAccountId.",
        },
      ]),
    );
  }

  const result = await engine.createClassificationRule({
    ledgerId,
    ruleType: body.ruleType,
    field: body.field,
    pattern: body.pattern,
    targetAccountId: body.targetAccountId,
    priority: body.priority,
    isPersonal: body.isPersonal,
    confidence: body.confidence,
  });
  if (!result.ok) return errorResponse(c, result.error);

  return created(c, result.value);
});

/** GET /v1/ledgers/:ledgerId/classification/rules/:ruleId — Get classification rule */
classificationRoutes.get("/rules/:ruleId", async (c) => {
  const engine = c.get("engine");
  const ruleId = c.req.param("ruleId")!;

  const result = await engine.getClassificationRule(ruleId);
  if (!result.ok) return errorResponse(c, result.error);

  return success(c, result.value);
});

/** PUT /v1/ledgers/:ledgerId/classification/rules/:ruleId — Update classification rule */
classificationRoutes.put("/rules/:ruleId", async (c) => {
  const engine = c.get("engine");
  const ruleId = c.req.param("ruleId")!;
  const body = await c.req.json();

  const result = await engine.updateClassificationRule(ruleId, {
    priority: body.priority,
    pattern: body.pattern,
    targetAccountId: body.targetAccountId,
    isPersonal: body.isPersonal,
    confidence: body.confidence,
  });
  if (!result.ok) return errorResponse(c, result.error);

  return success(c, result.value);
});

/** DELETE /v1/ledgers/:ledgerId/classification/rules/:ruleId — Delete classification rule */
classificationRoutes.delete("/rules/:ruleId", async (c) => {
  const engine = c.get("engine");
  const ruleId = c.req.param("ruleId")!;

  const result = await engine.deleteClassificationRule(ruleId);
  if (!result.ok) return errorResponse(c, result.error);

  return c.json({ data: { deleted: true } });
});

// ---------------------------------------------------------------------------
// Classify preview
// ---------------------------------------------------------------------------

/** POST /v1/ledgers/:ledgerId/classification/classify — Preview classification */
classificationRoutes.post("/classify", async (c) => {
  const engine = c.get("engine");
  const ledgerId = c.req.param("ledgerId")!;
  const body = await c.req.json();

  if (!body.description) {
    return errorResponse(
      c,
      createError(ErrorCode.VALIDATION_ERROR, "description is required", [
        {
          field: "description",
          suggestion: "Provide a transaction description to classify.",
        },
      ]),
    );
  }

  const result = await engine.classifyTransaction(ledgerId, {
    description: body.description,
    category: body.category,
    amount: body.amount,
  });
  if (!result.ok) return errorResponse(c, result.error);

  return success(c, result.value);
});

// ---------------------------------------------------------------------------
// Manual bank transaction classification
// ---------------------------------------------------------------------------

/** POST /v1/ledgers/:ledgerId/classification/bank-transactions/:bankTransactionId — Manually classify */
classificationRoutes.post("/bank-transactions/:bankTransactionId", async (c) => {
  const engine = c.get("engine");
  const bankTransactionId = c.req.param("bankTransactionId")!;
  const body = await c.req.json();

  if (!body.accountId) {
    return errorResponse(
      c,
      createError(ErrorCode.VALIDATION_ERROR, "accountId is required", [
        {
          field: "accountId",
          suggestion: "Provide the ledger account ID to classify this transaction to.",
        },
      ]),
    );
  }

  const result = await engine.classifyBankTransaction(
    bankTransactionId,
    body.accountId,
    body.isPersonal ?? false,
  );
  if (!result.ok) return errorResponse(c, result.error);

  return success(c, result.value);
});

// ---------------------------------------------------------------------------
// Merchant aliases
// ---------------------------------------------------------------------------

/** GET /v1/ledgers/:ledgerId/classification/aliases — List merchant aliases */
classificationRoutes.get("/aliases", async (c) => {
  const engine = c.get("engine");

  const result = await engine.listMerchantAliases();
  if (!result.ok) return errorResponse(c, result.error);

  return success(c, result.value);
});

/** POST /v1/ledgers/:ledgerId/classification/aliases — Add merchant alias */
classificationRoutes.post("/aliases", async (c) => {
  const engine = c.get("engine");
  const body = await c.req.json();

  if (!body.canonicalName || !body.alias) {
    return errorResponse(
      c,
      createError(ErrorCode.VALIDATION_ERROR, "canonicalName and alias are required", [
        {
          field: "canonicalName, alias",
          suggestion: "Provide the canonical merchant name and the alias to map to it.",
        },
      ]),
    );
  }

  const result = await engine.addMerchantAlias(body.canonicalName, body.alias);
  if (!result.ok) return errorResponse(c, result.error);

  return created(c, result.value);
});
