// ---------------------------------------------------------------------------
// Classification MCP tools — manage rules and classify transactions.
// ---------------------------------------------------------------------------

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { LedgerEngine } from "@ledge/core";
import { handleResult, toolOk } from "../lib/helpers.js";

export function registerClassificationTools(
  server: McpServer,
  engine: LedgerEngine,
): void {
  // -----------------------------------------------------------------------
  // list_classification_rules
  // -----------------------------------------------------------------------
  server.tool(
    "list_classification_rules",
    "List classification rules for a ledger. Rules automatically categorise bank transactions based on description patterns.",
    {
      ledgerId: z.string().describe("Ledger ID"),
      ruleType: z
        .enum(["exact", "contains", "regex", "amount_range"])
        .optional()
        .describe("Filter by rule type"),
      field: z
        .enum(["description", "merchant_name", "category"])
        .optional()
        .describe("Filter by field the rule matches against"),
      autoGenerated: z
        .boolean()
        .optional()
        .describe("Filter by whether the rule was auto-generated from user classifications"),
    },
    async ({ ledgerId, ruleType, field, autoGenerated }) => {
      const result = await engine.listClassificationRules(ledgerId, {
        ruleType,
        field,
        autoGenerated,
      });
      return handleResult(result);
    },
  );

  // -----------------------------------------------------------------------
  // create_classification_rule
  // -----------------------------------------------------------------------
  server.tool(
    "create_classification_rule",
    "Create a classification rule that automatically categorises bank transactions matching a pattern to a target account.",
    {
      ledgerId: z.string().describe("Ledger ID"),
      ruleType: z
        .enum(["exact", "contains", "regex", "amount_range"])
        .describe("Match type: exact (full match), contains (substring), regex, or amount_range"),
      field: z
        .enum(["description", "merchant_name", "category"])
        .describe("Which transaction field to match against"),
      pattern: z.string().describe("The pattern to match (e.g. 'AWS' for contains, 'AMAZON WEB SERVICES' for exact)"),
      targetAccountId: z.string().describe("Ledger account ID to classify matching transactions to"),
      priority: z.number().int().optional().describe("Rule priority (lower = higher priority, default 100)"),
      isPersonal: z.boolean().optional().describe("Whether matching transactions are personal expenses (default false)"),
      confidence: z.number().min(0).max(1).optional().describe("Classification confidence 0-1 (default 1.0)"),
    },
    async ({ ledgerId, ruleType, field, pattern, targetAccountId, priority, isPersonal, confidence }) => {
      const result = await engine.createClassificationRule({
        ledgerId,
        ruleType,
        field,
        pattern,
        targetAccountId,
        priority,
        isPersonal,
        confidence,
      });
      return handleResult(result);
    },
  );

  // -----------------------------------------------------------------------
  // classify_transaction
  // -----------------------------------------------------------------------
  server.tool(
    "classify_transaction",
    "Preview how a transaction description would be classified by the rules engine. Returns the matching account, confidence score, and which rule/layer matched.",
    {
      ledgerId: z.string().describe("Ledger ID"),
      description: z.string().describe("Transaction description to classify"),
      category: z.string().optional().describe("Transaction category (if available from bank feed)"),
      amount: z.number().optional().describe("Transaction amount in cents (for amount_range rules)"),
    },
    async ({ ledgerId, description, category, amount }) => {
      const result = await engine.classifyTransaction(ledgerId, {
        description,
        category,
        amount,
      });
      if (!result.ok) return handleResult(result);

      if (result.value === null) {
        return toolOk({
          classified: false,
          message: "No matching classification rule found for this description.",
        });
      }

      return toolOk({
        classified: true,
        ...result.value,
      });
    },
  );

  // -----------------------------------------------------------------------
  // classify_bank_transaction
  // -----------------------------------------------------------------------
  server.tool(
    "classify_bank_transaction",
    "Manually classify a bank transaction to a ledger account. If the same description has been classified to the same account twice, an auto-generated rule is created.",
    {
      bankTransactionId: z.string().describe("Bank transaction ID to classify"),
      accountId: z.string().describe("Ledger account ID to classify to"),
      isPersonal: z.boolean().optional().describe("Whether this is a personal expense (default false)"),
    },
    async ({ bankTransactionId, accountId, isPersonal }) => {
      const result = await engine.classifyBankTransaction(
        bankTransactionId,
        accountId,
        isPersonal ?? false,
      );
      return handleResult(result);
    },
  );

  // -----------------------------------------------------------------------
  // list_merchant_aliases
  // -----------------------------------------------------------------------
  server.tool(
    "list_merchant_aliases",
    "List all merchant aliases. Aliases normalise bank transaction descriptions to canonical merchant names for better classification matching.",
    {},
    async () => {
      const result = await engine.listMerchantAliases();
      return handleResult(result);
    },
  );
}
